### ISSUE TITLE
File shp del comune di Roma zippato

### ISSUE THREAD

**Issue by alesarrett** [pcm-dpc/DPC-Aggregati-Strutturali-ITI-Centro#7]
Il file .shp del Comune di Roma è salvato come Roma-shp.zip, il che può causare degli errori di importazione/integrazione quando si cerca di unire i vari shapefile per provincia o per Regione.
Non so se c'è un motivo specifico per cui è stato salvato in questo modo, ma credo sarebbe più utile estrarlo e lasciare nel repository direttamente il file contenuto in esso, Roma.shp

**Comment by pierluigicara** [comment]
Ciao @alesarrett, purtroppo è l'unico file (in tutta Italia) che eccede il limite imposto da github per la dimensione massima di un singolo file (100Mb) e quindi non c'è alternativa.
